# Generated by Django 4.2.20 on 2025-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('نشست', 'نشست'), ('دوره', 'دوره'), ('ورکشاپ', 'ورکشاپ'), ('همایش', 'همایش')], default='نشست', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'full_name')},
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='note',
        ),
    ]
