# Generated by Django 4.2.20 on 2025-10-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_category_eventtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
