# Generated by Django 4.2.20 on 2025-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_participant_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance',
            field=models.CharField(blank=True, help_text='✅ یا ❌', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ برگزاری جلسه\u200cی پیش\u200cرو (برای یادآوری خودکار)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'participant')},
        ),
    ]
