# Generated by Django 4.2.20 on 2025-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_attendance_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ برگزاری جلسه پیش\u200cرو', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attendance',
            field=models.CharField(blank=True, choices=[('present', '✅ حاضر'), ('absent', '❌ غایب'), ('unknown', '⏳ نامشخص')], default='unknown', max_length=10),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
