# Generated by Django 4.2.20 on 2025-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='event_attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
