# Generated by Django 5.2.7 on 2025-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_attachment_alter_event_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='event_files/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_files/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
