# Generated by Django 5.2.7 on 2025-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_files/'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
