# Generated by Django 5.2.7 on 2025-10-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_reminder_image_event_reminder_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
