# Generated by Django 4.2.20 on 2025-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_registration_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='year',
        ),
        migrations.AddField(
            model_name='participant',
            name='know_us',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='related_experiences',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
