# Generated by Django 4.2.20 on 2025-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_participant_year_participant_know_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
