# Generated by Django 4.2.20 on 2025-10-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_participant_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='year',
        ),
    ]
