# Generated by Django 5.2.7 on 2025-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_participant_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='event',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
