# Generated by Django 5.2.7 on 2025-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_reminder_sent_event_last_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='registration',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
